name: Enforce PR Reviews

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  check-review:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR approval status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request ? context.payload.pull_request.number : context.payload.pull_request_review.pull_request_number;
            
            // Get reviews
            const reviews = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number: prNumber,
            });
            
            // Check for approvals
            const approvals = reviews.data.filter(review => review.state === 'APPROVED');
            const hasApproval = approvals.length > 0;
            
            // Create status check
            const sha = context.payload.pull_request ? context.payload.pull_request.head.sha : 
                       (context.payload.pull_request_review ? context.payload.pull_request_review.commit_id : undefined);
            
            if (sha) {
              const checkName = 'PR Approval Required';
              const conclusion = hasApproval ? 'success' : 'failure';
              const title = hasApproval ? 'PR được phê duyệt ✅' : 'PR cần được review và phê duyệt ❌';
              const summary = hasApproval 
                ? `PR này đã được phê duyệt bởi ${approvals.map(a => '@' + a.user.login).join(', ')}`
                : 'PR này cần ít nhất 1 approval trước khi merge. Vui lòng yêu cầu team review.';
                
              await github.rest.checks.create({
                owner,
                repo,
                name: checkName,
                head_sha: sha,
                status: 'completed',
                conclusion: conclusion,
                output: {
                  title: title,
                  summary: summary
                }
              });
            }
